name: OptionChain Bot Runner

permissions:
  contents: write  # allow committing back

on:
  schedule:
    - cron: "*/1 3-12 * * 1-6"  # Every 1 min from 08:30-17:30 IST approx (adjust if needed)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          MODE: ${{ secrets.MODE }}
          CAPITAL: ${{ secrets.CAPITAL }}
          INDICES: "NIFTY,BANKNIFTY"
          GIT_NAME: ${{ secrets.GIT_NAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: |
          python bot.py
      - name: Commit trade_log if changed
        run: |
          git config user.name "${{ secrets.GIT_NAME }}"
          git config user.email "${{ secrets.GIT_EMAIL }}"
          if git status --porcelain | grep trade_log.json; then
            git add trade_log.json
            git commit -m "Update trade_log"
            git push
          else
            echo "No trade_log changes"
          fi
